import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { IntroProvider } from "../components/animata/IntroContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IllUSION TECH",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.png" type="image/png" />
      </head>
      <body className={inter.className}>
        <IntroProvider>
          <Header />
          <NextTopLoader color="linear-gradient(to right, rgb(251, 113, 133), rgb(217, 70, 239), rgb(99, 102, 241))" />
          {children}
          <Footer />
        </IntroProvider>
      </body>
    </html>
  );
}
