import type { Metadata } from "next";
// import { ThemeProvider } from "next-themes";
import Header from "@/components/Header";
// import Transition from "@/components/Transition";
import Footer from "@/components/Footer";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IllUSION TECH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        
        {children}
        
        
        <Footer />
      </body>
    </html>
  );
}
