services:
  # nextjs service
  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://0.0.0.0:3000
    depends_on:
      - flaskapp

  # flask service
  flaskapp:
    container_name: flaskapp
    image: flaskapp:1.0.0
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - 8001:8001
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8001
      - DATABASE_URL=postgresql+psycopg2://postgres:Gourav@db:5432/website
    depends_on:
      - db

  # db service
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gourav
      POSTGRES_DB: website
    ports:
      - 5000:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ./db-init:/docker-entrypoint-initdb.d

volumes:
  pgdata: {}
